# Generated by Django 6.0 on 2025-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
