# Generated by Django 6.0 on 2025-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_onetimepassword_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
